### PR TITLE
Subbuffer

### PR DESCRIPTION
**Pull request by wrexroad**
BitBuffer#subbuffer return a new BitBuffer containing the bits from the specified section of the original BitBuffer. Uses same arguments as String#substring.

### CODE REVIEW

**Comment by wiedi** [comment]
If this would interpret negative indexes from the end it could also be called `slice()` so it is more familiear to users of the Buffer api. What do you think?

Otherwise I think this is fine.

**Comment by wrexroad** [comment]
The negative indices are a good idea. As I said in my comment on #6, I still think subbuffer is a better name than slice since Buffer.slice uses the same underlying memory, whereas BitBuffer.subbuffer returns a completely new buffer. But I if you feel strongly about the name, then that's fine.

**Comment by wiedi** [comment]
Ah, true! I was thinking if there would be a good way to keep memory shared but could not come up with something nice. Let's keep subbuffer then :)

**Comment by wiedi** [comment]
Also if sharing is needed and byte alignment is fine one can just use `new BitBuffer(l, otherbb.buffer.slice(s,e))` so I guess that's easy enough.

**Pull request closed without merging**
